collection:
  - meta_property_name: is_popular
    display_meta_properties:
      - title
      - createdAt
    order: desc

  - meta_property_name: is_home_teaser
    display_meta_properties:
      - title
      - description
      - href
